### ISSUE TITLE
Simulate whole samples

### ISSUE THREAD

**Issue by jcgrenier** [adimitromanolakis/sim1000G#1]
Hello! Thanks for that tool! 
Is there a way to directly simulate a whole sample that will have a genetic background that will look normal? The only thing I was able to do for the moment is to simulate chromosome per chromosome, so I suppose that I won't be able to concatenate all the chromosomes together in the end without looking at weird samples.

Thanks for the help.
Best,

**Comment by adimitromanolakis** [comment]
Hi, 
you can concatenate all the chromosomes, it is not a problem and will result in a normal looking sample.

Best,
Apostolos

**Comment by jcgrenier** [comment]
Hello @adimitromanolakis , thanks for the quick answer! I'll give it a try and will come back to you if we are encountering any issues with that! Thanks!

**Comment by jcgrenier** [comment]
Hum, while thinking about it, how does it work exactly. How is one samples simulated? Does it take 2 different samples as parents of the samples and create a new one, or it's more random than this?

Thanks for your help!

**Comment by adimitromanolakis** [comment]
Depends, if you simulate independant samples then there are no parents but generated randomly based on a model of the LD and allele frequencies of the markers. If you generate family data, then 2 individuals have to be the parents.

**Comment by jcgrenier** [comment]
Alright, that's basically what I wanted to do. Thanks a lot for your help!
