### ISSUE TITLE
Se

### ISSUE THREAD

**Issue by violafanfani** [adimitromanolakis/sim1000G#2]
Hello, 
I am trying to run a simulation on the chr22 and I am repeatedly getting a segmentation fault error. I am not sure if I am doing something wrong or if there is a bug somewhere. 

I am running an adapted version of the script here (https://cran.r-project.org/web/packages/sim1000G/vignettes/ExtractingRegionsForSimulation.html) using only the EUR population. The vcf file is the whole chr22 ( filtered by bcftool as described ). 
I am running it on a cluster on a single core with 92Gb of memory, but the same happened also with 128Gb memory and more cores. 

I am fairly sure the code is working as I can run it with small region of chr22 ( as in the chr4 example you provide). The id_ped are the pedigrees of the EUR populations. 

Is there anything I've missed from the documentation? 

Thanks for the attention, I attach the log of the job in question.

Cheers
Viola

This is the log of the job:
++++++++++++++++++
```
.....
Parsed with column specification:
cols(
  .default = col_character(),
  `#CHROM` = col_double(),
  POS = col_double(),
  QUAL = col_double()
)
See spec(...) for full column specifications.

 *** caught segfault ***
address 0x2b8d347b7220, cause 'memory not mapped'

Traceback:
 1: cor(dat)
 2: haplodata(haplomatrix[, polymorphic])
 3: startSimulation(vcf, subset = id_ped)
An irrecoverable exception occurred. R is aborting now ...
/bin/bash: line 1: 23945 Segmentation fault      (core dumped)
.....

```

**Comment by adimitromanolakis** [comment]
Hi Viola,

how many variants are present in the file? The current version of sim1000G
is not possible to load more than a few thousand variants.

Apostolos

**Comment by violafanfani** [comment]
Hi Apostolos,
Thank you for the quick reply.
I was mistakenly using more than 300K. However I would definitively need more than 10K, do you know if that is possible? What is the limit due to? 
Thanks
Viola

**Comment by adimitromanolakis** [comment]
Hi Viola,

it should be possible but it will require some more computer time and
memory. We haven't tested it with more than ~15000 markers.

Thanks,

Apostolos
