### ISSUE TITLE
Error in eigen(sigma, symmetric = TRUE) : 0 x 0 matrix

### ISSUE THREAD

**Issue by gpsccs** [adimitromanolakis/sim1000G#3]
when I use the function :startSimulation, it occour this error

**Comment by gpsccs** [comment]
> vcf<-readVCF(vcf_file,maxNumberOfVariants = 600 , min_maf = 0.05, max_maf = 1)
[#.......] Reading VCF file..
Parsed with column specification:
cols(
  .default = col_character(),
  POS = col_double(),
  QUAL = col_double()
)
See spec(...) for full column specifications.
[##......] Chromosome:   chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chr23 chr24  Mbp:  0.000332  Region Size:  49568.59 kb  Num of individuals: 200 
[##......] Before filtering  Num of variants: 105179 Num of individuals: 200 
[###.....] After filtering  Num of variants: 600 Num of individuals: 200 
There were 50 or more warnings (use warnings() to see the first 50)
> startSimulation(vcf, totalNumberOfIndividuals = 1000)
[#####...] Creating SIM object
Error in eigen(sigma, symmetric = TRUE) : 0 x 0 matrix

**Comment by adimitromanolakis** [comment]
Hi,
it seems that you are using a multi-chromosome file as input. sim1000G does
not support that. Can you try using a file from a single chromosome?
